version: "3"

services:
  mysqlsrv:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      # MYSQL_DATABASE: "rest_with_spring_boot"
    ports:
      - "3306:3306"
    volumes:
      - /home/gdarlan/Documentos/cursos/microservices-com-kotlin/volumes:/var/lib/mysql
    networks:
      - mysql-network

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - mysql-network

  zookeeper:
    image: zookeeper:3.8.0-temurin
    ports:
      - "10000:8080"
      - "2181:2181"
    environment:
      - ZOO_ADMINSERVER_ENABLED=true
    security_opt:
      - seccomp:unconfined
    # deploy:
    #   resources:
    #     limits:
    #       memory: 4096M
    #     reservations:
    #       memory: 4096M

networks:
  mysql-network:
    driver: bridge
